GET http://localhost:3000/api/users

### LOGIN AND CREATE TOKEN
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "marko@gmail.com",
    "password": "marko123"

}

### REFRESH TOKEN
POST http://localhost:3000/api/access-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjA4MDQ1ODU5LCJleHAiOjE2MDgwNDk0NTl9.AVcijY75yc4RVzTHzoUxzH6CjsGh6n2jYura8ZYT_XE"
}

### INVALIDATE REFRESH TOKEN
DELETE http://localhost:3000/api/invalidate
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjA1NTMyMTcxfQ.3STAHsaCHAc1Nb4KBOg2LOyxlhdXyuRDCEM_fKQ8ghE"
}


### ACCESS TOKEN PROTECTED ROUTE
GET http://localhost:3000/api
